name: Deploy Dog
on: workflow_dispatch
jobs:
    deploy-job:
      runs-on: ubuntu-latest
      permissions:
        contents: 'read'
        id-token: 'write'
      steps:
        - name: Get code
          uses: actions/checkout@v4.2.2
        
        - name: Authenticate Google Cloud
          uses: google-github-actions/auth@v2
          with:
            service_account: 1026231733241-compute@developer.gserviceaccount.com
            project_id: devops-team-13-171401
            workload_identity_provider: projects/1026231733241/locations/global/workloadIdentityPools/github/providers/my-repo
        
        # Step 3: Install Google Cloud SDK
        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
          with:
            project_id: devops-team-13-171401
        
        # Step 4: Deploy the Docker image to Cloud Run
        - name: Deploy to Cloud Run
          run: |
            gcloud run deploy game-server-service-from-command-line \
              --image=europe-west6-docker.pkg.dev/devops-team-13-171401/cloud-run-source-deploy/game-server-service-from-command-line:latest \
              --platform=managed \
              --region=europe-west6 \
              --allow-unauthenticated

        # Step 5: Get and print the service URL
        - name: Get service URL
          run: |
            SERVICE_URL=$(gcloud run services describe game-server-service-from-command-line \
              --platform=managed \
              --region=europe-west6 \
              --format='value(status.url)')
            echo "Service is running at: $SERVICE_URL"        
            